# Generated by Django 3.1.5 on 2021-11-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.TextField()),
                ('password', models.TextField()),
                ('uid', models.UUIDField(blank=True, default=None, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
