# Generated by Django 3.1.5 on 2021-11-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='post',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
