# Generated by Django 3.1.5 on 2021-11-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='post',
            field=models.CharField(choices=[(10, 'SUPERADMIN'), (5, 'ACCOUNTS'), (7, 'ADMIN'), (3, 'STAFF'), (1, 'LIBRARY')], default=1, max_length=2),
        ),
    ]
